/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import FileManager.FileManager;
import java.io.File;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author andre
 */
public class Parameters extends javax.swing.JFrame {

    private static Parameters configuration;
//    private final Home homeInstance = Home.getHomeInstance();
    private int duration;
    private int deadline;
    private File selectedFile = Home.getSelectedFile();
    private FileManager fileManager = new FileManager();
    /**
     * Creates new form Parameters
     */
    public Parameters() {
        initComponents();
         // properties gui
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setTitle("Params");
        // Inicializar los valores de HOME
        this.initValues();
    }
    
    public static synchronized Parameters getInstance() {
        if (configuration == null) {
            configuration = new Parameters();
        }
        return configuration;
    }
    
    private void initValues(){
        if (Home.getFactory0() != null && Home.getFactory1() != null) {
            this.duration = (int) Home.getDuration() / 1000;
            this.deadline = Home.getDeadline();
            this.durationValue.setText(String.valueOf(duration));
            this.deadlineValue.setText(String.valueOf(deadline));
        }
    }
    
    private void updateBtnParams() {
        if (this.duration == 1) {
            this.decreaseDayValue.setEnabled(false);
            this.decreaseDayValue.setFocusable(false);
        } else {
            this.decreaseDayValue.setEnabled(true);
            this.decreaseDayValue.setFocusable(true);
        }

        if (this.deadline == 1) {
            this.decreaseDeadlineValue.setEnabled(false);
            this.decreaseDeadlineValue.setFocusable(false);
        } else {
            this.decreaseDeadlineValue.setEnabled(true);
            this.decreaseDeadlineValue.setFocusable(true);
        }
    }
    
    private boolean canDecreaseDayBtn() {
        return this.duration > 1;
    }
    
    private boolean canDecreaseDeadlineBtn() {
        return this.deadline > 1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        deadlineValue = new javax.swing.JTextField();
        durationValue = new javax.swing.JTextField();
        increaseDayValue = new javax.swing.JButton();
        decreaseDayValue = new javax.swing.JButton();
        increaseDeadlineValue = new javax.swing.JButton();
        decreaseDeadlineValue = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        decreaseMOBO0 = new javax.swing.JButton();
        jTextField7 = new javax.swing.JTextField();
        increaseMOBO0 = new javax.swing.JButton();
        jPanel19 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        decreaseCPU0 = new javax.swing.JButton();
        jTextField8 = new javax.swing.JTextField();
        increaseCPU0 = new javax.swing.JButton();
        jPanel20 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        decreaseRAM0 = new javax.swing.JButton();
        jTextField9 = new javax.swing.JTextField();
        increaseRAM0 = new javax.swing.JButton();
        jPanel21 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        decreasePSU0 = new javax.swing.JButton();
        jTextField10 = new javax.swing.JTextField();
        increasePSU0 = new javax.swing.JButton();
        jPanel22 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        decreaseGPU0 = new javax.swing.JButton();
        jTextField11 = new javax.swing.JTextField();
        increaseGPU0 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        decreaseMOBO1 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        increaseMOBO1 = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        decreaseCPU1 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        increaseCPU1 = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        decreaseRAM1 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        increaseRAM1 = new javax.swing.JButton();
        jPanel16 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        decreasePSU1 = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();
        increasePSU1 = new javax.swing.JButton();
        jPanel17 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        decreaseGPU1 = new javax.swing.JButton();
        jTextField6 = new javax.swing.JTextField();
        increaseGPU1 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        saveConfigBtn = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 88, 137));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("HP Simplified", 1, 21)); // NOI18N
        jLabel4.setText("Plazo de días de entrega:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 240, -1));

        jLabel6.setFont(new java.awt.Font("HP Simplified", 1, 21)); // NOI18N
        jLabel6.setText("Duración de los días:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 200, -1));

        deadlineValue.setFont(new java.awt.Font("HP Simplified", 1, 14)); // NOI18N
        deadlineValue.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        deadlineValue.setText("0");
        deadlineValue.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        deadlineValue.setFocusable(false);
        jPanel1.add(deadlineValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 30, 40, 30));

        durationValue.setFont(new java.awt.Font("HP Simplified", 1, 14)); // NOI18N
        durationValue.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        durationValue.setText("0");
        durationValue.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        durationValue.setFocusable(false);
        durationValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                durationValueActionPerformed(evt);
            }
        });
        jPanel1.add(durationValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 40, 30));

        increaseDayValue.setBackground(new java.awt.Color(75, 54, 33));
        increaseDayValue.setFont(new java.awt.Font("HP Simplified", 1, 14)); // NOI18N
        increaseDayValue.setForeground(new java.awt.Color(255, 255, 255));
        increaseDayValue.setText("+");
        increaseDayValue.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        increaseDayValue.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        increaseDayValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                increaseDayValueActionPerformed(evt);
            }
        });
        jPanel1.add(increaseDayValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 30, 30));

        decreaseDayValue.setBackground(new java.awt.Color(75, 54, 33));
        decreaseDayValue.setFont(new java.awt.Font("HP Simplified", 1, 14)); // NOI18N
        decreaseDayValue.setForeground(new java.awt.Color(255, 255, 255));
        decreaseDayValue.setText("-");
        decreaseDayValue.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        decreaseDayValue.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        decreaseDayValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decreaseDayValueActionPerformed(evt);
            }
        });
        jPanel1.add(decreaseDayValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 30, 30));

        increaseDeadlineValue.setBackground(new java.awt.Color(75, 54, 33));
        increaseDeadlineValue.setFont(new java.awt.Font("HP Simplified", 1, 14)); // NOI18N
        increaseDeadlineValue.setForeground(new java.awt.Color(255, 255, 255));
        increaseDeadlineValue.setText("+");
        increaseDeadlineValue.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        increaseDeadlineValue.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        increaseDeadlineValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                increaseDeadlineValueActionPerformed(evt);
            }
        });
        jPanel1.add(increaseDeadlineValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 30, 30, 30));

        decreaseDeadlineValue.setBackground(new java.awt.Color(75, 54, 33));
        decreaseDeadlineValue.setFont(new java.awt.Font("HP Simplified", 1, 14)); // NOI18N
        decreaseDeadlineValue.setForeground(new java.awt.Color(255, 255, 255));
        decreaseDeadlineValue.setText("-");
        decreaseDeadlineValue.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        decreaseDeadlineValue.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        decreaseDeadlineValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decreaseDeadlineValueActionPerformed(evt);
            }
        });
        jPanel1.add(decreaseDeadlineValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 30, 30, 30));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 790, 80));

        jPanel5.setBackground(new java.awt.Color(222, 222, 242));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("HP Simplified", 1, 18)); // NOI18N
        jLabel5.setText("Micro-Star International");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 210, -1));

        jLabel9.setFont(new java.awt.Font("Lucida Bright", 1, 16)); // NOI18N
        jLabel9.setText("Máximo:");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 100, 20));

        jPanel18.setBackground(new java.awt.Color(109, 86, 164));
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 16)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Trabajador Placa Base:");
        jPanel18.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 20));

        decreaseMOBO0.setBackground(new java.awt.Color(214, 125, 178));
        decreaseMOBO0.setFont(new java.awt.Font("HP Simplified", 1, 12)); // NOI18N
        decreaseMOBO0.setForeground(new java.awt.Color(255, 255, 255));
        decreaseMOBO0.setText("-");
        decreaseMOBO0.setBorder(null);
        decreaseMOBO0.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel18.add(decreaseMOBO0, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 30, 20));

        jTextField7.setFont(new java.awt.Font("HP Simplified", 1, 12)); // NOI18N
        jTextField7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField7.setText("0");
        jTextField7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextField7.setFocusable(false);
        jPanel18.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 30, -1));

        increaseMOBO0.setBackground(new java.awt.Color(214, 125, 178));
        increaseMOBO0.setFont(new java.awt.Font("HP Simplified", 1, 12)); // NOI18N
        increaseMOBO0.setForeground(new java.awt.Color(255, 255, 255));
        increaseMOBO0.setText("+");
        increaseMOBO0.setBorder(null);
        increaseMOBO0.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel18.add(increaseMOBO0, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 30, 20));

        jPanel5.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 360, 40));

        jPanel19.setBackground(new java.awt.Color(109, 86, 164));
        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 16)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Trabajador CPU:");
        jPanel19.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 20));

        decreaseCPU0.setBackground(new java.awt.Color(214, 125, 178));
        decreaseCPU0.setFont(new java.awt.Font("HP Simplified", 1, 12)); // NOI18N
        decreaseCPU0.setForeground(new java.awt.Color(255, 255, 255));
        decreaseCPU0.setText("-");
        decreaseCPU0.setBorder(null);
        decreaseCPU0.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel19.add(decreaseCPU0, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 30, 20));

        jTextField8.setFont(new java.awt.Font("HP Simplified", 1, 12)); // NOI18N
        jTextField8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField8.setText("0");
        jTextField8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextField8.setFocusable(false);
        jPanel19.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 30, -1));

        increaseCPU0.setBackground(new java.awt.Color(214, 125, 178));
        increaseCPU0.setFont(new java.awt.Font("HP Simplified", 1, 12)); // NOI18N
        increaseCPU0.setForeground(new java.awt.Color(255, 255, 255));
        increaseCPU0.setText("+");
        increaseCPU0.setBorder(null);
        increaseCPU0.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel19.add(increaseCPU0, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 30, 20));

        jPanel5.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 360, 40));

        jPanel20.setBackground(new java.awt.Color(109, 86, 164));
        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 16)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Trabajador RAM:");
        jPanel20.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 20));

        decreaseRAM0.setBackground(new java.awt.Color(214, 125, 178));
        decreaseRAM0.setFont(new java.awt.Font("HP Simplified", 1, 12)); // NOI18N
        decreaseRAM0.setForeground(new java.awt.Color(255, 255, 255));
        decreaseRAM0.setText("-");
        decreaseRAM0.setBorder(null);
        decreaseRAM0.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel20.add(decreaseRAM0, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 30, 20));

        jTextField9.setFont(new java.awt.Font("HP Simplified", 1, 12)); // NOI18N
        jTextField9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField9.setText("0");
        jTextField9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextField9.setFocusable(false);
        jPanel20.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 30, -1));

        increaseRAM0.setBackground(new java.awt.Color(214, 125, 178));
        increaseRAM0.setFont(new java.awt.Font("HP Simplified", 1, 12)); // NOI18N
        increaseRAM0.setForeground(new java.awt.Color(255, 255, 255));
        increaseRAM0.setText("+");
        increaseRAM0.setBorder(null);
        increaseRAM0.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel20.add(increaseRAM0, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 30, 20));

        jPanel5.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 360, 40));

        jPanel21.setBackground(new java.awt.Color(109, 86, 164));
        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 16)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Trabajador Fuente:");
        jPanel21.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 20));

        decreasePSU0.setBackground(new java.awt.Color(214, 125, 178));
        decreasePSU0.setFont(new java.awt.Font("HP Simplified", 1, 12)); // NOI18N
        decreasePSU0.setForeground(new java.awt.Color(255, 255, 255));
        decreasePSU0.setText("-");
        decreasePSU0.setBorder(null);
        decreasePSU0.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel21.add(decreasePSU0, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 30, 20));

        jTextField10.setFont(new java.awt.Font("HP Simplified", 1, 12)); // NOI18N
        jTextField10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField10.setText("0");
        jTextField10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextField10.setFocusable(false);
        jPanel21.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 30, -1));

        increasePSU0.setBackground(new java.awt.Color(214, 125, 178));
        increasePSU0.setFont(new java.awt.Font("HP Simplified", 1, 12)); // NOI18N
        increasePSU0.setForeground(new java.awt.Color(255, 255, 255));
        increasePSU0.setText("+");
        increasePSU0.setBorder(null);
        increasePSU0.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel21.add(increasePSU0, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 30, 20));

        jPanel5.add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 360, 40));

        jPanel22.setBackground(new java.awt.Color(109, 86, 164));
        jPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 16)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Trabajador Gráfica:");
        jPanel22.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 20));

        decreaseGPU0.setBackground(new java.awt.Color(214, 125, 178));
        decreaseGPU0.setFont(new java.awt.Font("HP Simplified", 1, 12)); // NOI18N
        decreaseGPU0.setForeground(new java.awt.Color(255, 255, 255));
        decreaseGPU0.setText("-");
        decreaseGPU0.setBorder(null);
        decreaseGPU0.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel22.add(decreaseGPU0, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 30, 20));

        jTextField11.setFont(new java.awt.Font("HP Simplified", 1, 12)); // NOI18N
        jTextField11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField11.setText("0");
        jTextField11.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextField11.setFocusable(false);
        jPanel22.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 30, -1));

        increaseGPU0.setBackground(new java.awt.Color(214, 125, 178));
        increaseGPU0.setFont(new java.awt.Font("HP Simplified", 1, 12)); // NOI18N
        increaseGPU0.setForeground(new java.awt.Color(255, 255, 255));
        increaseGPU0.setText("+");
        increaseGPU0.setBorder(null);
        increaseGPU0.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel22.add(increaseGPU0, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 30, 20));

        jPanel5.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 360, 40));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 380, 420));

        jPanel6.setBackground(new java.awt.Color(222, 222, 242));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("HP Simplified", 1, 18)); // NOI18N
        jLabel7.setText("Hewlett-Packard");
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 150, -1));

        jLabel8.setFont(new java.awt.Font("Lucida Bright", 1, 16)); // NOI18N
        jLabel8.setText("Máximo:");
        jPanel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 90, -1));

        jPanel13.setBackground(new java.awt.Color(109, 86, 164));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Trabajador Placa Base:");
        jPanel13.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 20));

        decreaseMOBO1.setBackground(new java.awt.Color(214, 125, 178));
        decreaseMOBO1.setFont(new java.awt.Font("HP Simplified", 1, 12)); // NOI18N
        decreaseMOBO1.setForeground(new java.awt.Color(255, 255, 255));
        decreaseMOBO1.setText("-");
        decreaseMOBO1.setBorder(null);
        decreaseMOBO1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel13.add(decreaseMOBO1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 30, 20));

        jTextField2.setFont(new java.awt.Font("HP Simplified", 1, 12)); // NOI18N
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("0");
        jTextField2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextField2.setFocusable(false);
        jPanel13.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 30, -1));

        increaseMOBO1.setBackground(new java.awt.Color(214, 125, 178));
        increaseMOBO1.setFont(new java.awt.Font("HP Simplified", 1, 12)); // NOI18N
        increaseMOBO1.setForeground(new java.awt.Color(255, 255, 255));
        increaseMOBO1.setText("+");
        increaseMOBO1.setBorder(null);
        increaseMOBO1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel13.add(increaseMOBO1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 30, 20));

        jPanel6.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 350, 40));

        jPanel14.setBackground(new java.awt.Color(109, 86, 164));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Trabajador CPU:");
        jPanel14.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 20));

        decreaseCPU1.setBackground(new java.awt.Color(214, 125, 178));
        decreaseCPU1.setFont(new java.awt.Font("HP Simplified", 1, 12)); // NOI18N
        decreaseCPU1.setForeground(new java.awt.Color(255, 255, 255));
        decreaseCPU1.setText("-");
        decreaseCPU1.setBorder(null);
        decreaseCPU1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel14.add(decreaseCPU1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 30, 20));

        jTextField3.setFont(new java.awt.Font("HP Simplified", 1, 12)); // NOI18N
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("0");
        jTextField3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextField3.setFocusable(false);
        jPanel14.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 30, -1));

        increaseCPU1.setBackground(new java.awt.Color(214, 125, 178));
        increaseCPU1.setFont(new java.awt.Font("HP Simplified", 1, 12)); // NOI18N
        increaseCPU1.setForeground(new java.awt.Color(255, 255, 255));
        increaseCPU1.setText("+");
        increaseCPU1.setBorder(null);
        increaseCPU1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel14.add(increaseCPU1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 30, 20));

        jPanel6.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 350, 40));

        jPanel15.setBackground(new java.awt.Color(109, 86, 164));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 16)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Trabajador RAM:");
        jPanel15.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 20));

        decreaseRAM1.setBackground(new java.awt.Color(214, 125, 178));
        decreaseRAM1.setFont(new java.awt.Font("HP Simplified", 1, 12)); // NOI18N
        decreaseRAM1.setForeground(new java.awt.Color(255, 255, 255));
        decreaseRAM1.setText("-");
        decreaseRAM1.setBorder(null);
        decreaseRAM1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel15.add(decreaseRAM1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 30, 20));

        jTextField4.setFont(new java.awt.Font("HP Simplified", 1, 12)); // NOI18N
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setText("0");
        jTextField4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextField4.setFocusable(false);
        jPanel15.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 30, -1));

        increaseRAM1.setBackground(new java.awt.Color(214, 125, 178));
        increaseRAM1.setFont(new java.awt.Font("HP Simplified", 1, 12)); // NOI18N
        increaseRAM1.setForeground(new java.awt.Color(255, 255, 255));
        increaseRAM1.setText("+");
        increaseRAM1.setBorder(null);
        increaseRAM1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel15.add(increaseRAM1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 30, 20));

        jPanel6.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 350, 40));

        jPanel16.setBackground(new java.awt.Color(109, 86, 164));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 16)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Trabajador Fuente:");
        jPanel16.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 20));

        decreasePSU1.setBackground(new java.awt.Color(214, 125, 178));
        decreasePSU1.setFont(new java.awt.Font("HP Simplified", 1, 12)); // NOI18N
        decreasePSU1.setForeground(new java.awt.Color(255, 255, 255));
        decreasePSU1.setText("-");
        decreasePSU1.setBorder(null);
        decreasePSU1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel16.add(decreasePSU1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 30, 20));

        jTextField5.setFont(new java.awt.Font("HP Simplified", 1, 12)); // NOI18N
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.setText("0");
        jTextField5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextField5.setFocusable(false);
        jPanel16.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 30, -1));

        increasePSU1.setBackground(new java.awt.Color(214, 125, 178));
        increasePSU1.setFont(new java.awt.Font("HP Simplified", 1, 12)); // NOI18N
        increasePSU1.setForeground(new java.awt.Color(255, 255, 255));
        increasePSU1.setText("+");
        increasePSU1.setBorder(null);
        increasePSU1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel16.add(increasePSU1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 30, 20));

        jPanel6.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 350, 40));

        jPanel17.setBackground(new java.awt.Color(109, 86, 164));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 16)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Trabajador Gráfica:");
        jPanel17.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 20));

        decreaseGPU1.setBackground(new java.awt.Color(214, 125, 178));
        decreaseGPU1.setFont(new java.awt.Font("HP Simplified", 1, 12)); // NOI18N
        decreaseGPU1.setForeground(new java.awt.Color(255, 255, 255));
        decreaseGPU1.setText("-");
        decreaseGPU1.setBorder(null);
        decreaseGPU1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel17.add(decreaseGPU1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 30, 20));

        jTextField6.setFont(new java.awt.Font("HP Simplified", 1, 12)); // NOI18N
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField6.setText("0");
        jTextField6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextField6.setFocusable(false);
        jPanel17.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 30, -1));

        increaseGPU1.setBackground(new java.awt.Color(214, 125, 178));
        increaseGPU1.setFont(new java.awt.Font("HP Simplified", 1, 12)); // NOI18N
        increaseGPU1.setForeground(new java.awt.Color(255, 255, 255));
        increaseGPU1.setText("+");
        increaseGPU1.setBorder(null);
        increaseGPU1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel17.add(increaseGPU1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 30, 20));

        jPanel6.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 350, 40));

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, 380, 420));

        jPanel8.setBackground(new java.awt.Color(122, 122, 220));
        jPanel8.setBorder(javax.swing.BorderFactory.createEmptyBorder(45, 45, 45, 45));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI.Assets/previous_icon.png"))); // NOI18N
        jLabel3.setText(" Volver");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel8.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 130, 40));

        jPanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, 170, 60));

        jPanel7.setBackground(new java.awt.Color(122, 122, 220));
        jPanel7.setBorder(javax.swing.BorderFactory.createEmptyBorder(45, 45, 45, 45));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        saveConfigBtn.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        saveConfigBtn.setForeground(new java.awt.Color(255, 255, 255));
        saveConfigBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        saveConfigBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI.Assets/ribbon_icon.png"))); // NOI18N
        saveConfigBtn.setText(" Guardar");
        saveConfigBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        saveConfigBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveConfigBtnMouseClicked(evt);
            }
        });
        jPanel7.add(saveConfigBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 150, 40));

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 550, 180, 60));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 850, 630));

        jPanel3.setBackground(new java.awt.Color(34, 34, 107));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI.Assets/parenthesis_icon.png"))); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 60, -1));

        jLabel11.setFont(new java.awt.Font("HP Simplified", 0, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("Configuración");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 210, 50));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveConfigBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveConfigBtnMouseClicked
        // TODO add your handling code here:
        try {
            this.fileManager.writeData(this.selectedFile);
            JOptionPane.showMessageDialog(this, "El archivo 'data' se guardó correctamente!");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al escribir el archivo");
        }
        
    }//GEN-LAST:event_saveConfigBtnMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        Home goBack = new Home();
        goBack.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void increaseDayValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_increaseDayValueActionPerformed
        // TODO add your handling code here:
        this.duration += 1;
        Home.setDuration(this.duration * 1000);
        this.durationValue.setText(String.valueOf(Home.getDuration() / 1000));
        this.updateBtnParams();
    }//GEN-LAST:event_increaseDayValueActionPerformed

    private void durationValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_durationValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_durationValueActionPerformed

    private void decreaseDayValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decreaseDayValueActionPerformed
        // TODO add your handling code here:
        if (this.canDecreaseDayBtn()) {
            this.duration -= 1;
            Home.setDuration(duration*1000);
            this.durationValue.setText(String.valueOf(Home.getDuration() / 1000));
        }
        this.updateBtnParams();
    }//GEN-LAST:event_decreaseDayValueActionPerformed

    private void decreaseDeadlineValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decreaseDeadlineValueActionPerformed
        // TODO add your handling code here:
        if (this.canDecreaseDeadlineBtn()) {
            this.deadline -= 1;
            Home.setDeadline(deadline);
            this.deadlineValue.setText(String.valueOf(Home.getDeadline()));
        }
        this.updateBtnParams();
    }//GEN-LAST:event_decreaseDeadlineValueActionPerformed

    private void increaseDeadlineValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_increaseDeadlineValueActionPerformed
        // TODO add your handling code here:
        this.deadline += 1;
        Home.setDeadline(this.deadline);
        this.deadlineValue.setText(String.valueOf(Home.getDeadline()));
        this.updateBtnParams();
    }//GEN-LAST:event_increaseDeadlineValueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Parameters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Parameters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Parameters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Parameters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Parameters().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField deadlineValue;
    private javax.swing.JButton decreaseCPU0;
    private javax.swing.JButton decreaseCPU1;
    private javax.swing.JButton decreaseDayValue;
    private javax.swing.JButton decreaseDeadlineValue;
    private javax.swing.JButton decreaseGPU0;
    private javax.swing.JButton decreaseGPU1;
    private javax.swing.JButton decreaseMOBO0;
    private javax.swing.JButton decreaseMOBO1;
    private javax.swing.JButton decreasePSU0;
    private javax.swing.JButton decreasePSU1;
    private javax.swing.JButton decreaseRAM0;
    private javax.swing.JButton decreaseRAM1;
    private javax.swing.JTextField durationValue;
    private javax.swing.JButton increaseCPU0;
    private javax.swing.JButton increaseCPU1;
    private javax.swing.JButton increaseDayValue;
    private javax.swing.JButton increaseDeadlineValue;
    private javax.swing.JButton increaseGPU0;
    private javax.swing.JButton increaseGPU1;
    private javax.swing.JButton increaseMOBO0;
    private javax.swing.JButton increaseMOBO1;
    private javax.swing.JButton increasePSU0;
    private javax.swing.JButton increasePSU1;
    private javax.swing.JButton increaseRAM0;
    private javax.swing.JButton increaseRAM1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel saveConfigBtn;
    // End of variables declaration//GEN-END:variables
}
